### PR TITLE
Format & update project for Elixir 1.14

### PR DESCRIPTION
**Pull request by zachallaun**
Hi friends!

This is a very neat project that I'd like to contribute to. This PR is primarily for developer quality-of-life and does not introduce any changes to the library. It adds support for Elixir 1.14/OTP 25, including updating the CI workflow, and I've run `mix format` on the entire project.

There's some additional refactoring and work I'd like to do, but as I wanted to start with formatting, I thought I would submit this PR first so that any future PR's are easier to review. (Any other work I do will branch off of this.)

### CODE REVIEW

**Comment by smetana** [comment]
Hi. Thank you for PR. We will do "mix format" and add support for 1.14 in next release. We won't track mix.lock though

**Comment by zachallaun** [comment]
Thanks for the quick feedback, @smetana!

Out of curiosity, could you share why mix.lock isn't being tracked? I'm having trouble finding any other libraries that _don't_ track it.

**Comment by smetana** [comment]
> Out of curiosity, could you share why mix.lock isn't being tracked? I'm having trouble finding any other libraries that _don't_ track it.

It's just a way to keep project updated. Always build it on CI with latest deps.

**Comment by zachallaun** [comment]
Thanks for looking things over. I'll try to split it up today.

The files are different (subtly), but having looked at the integration test runner, I don't think new test log files need to be created. Instead, I think the `canonicalize_output` function just needs to be updated to handle an extra newline that was added in the test output in Elixir 1.14.

**Comment by zachallaun** [comment]
I’m not going to have time to split this, so will close for now instead of letting it linger.

**Comment by smetana** [comment]
Hi. We released v0.10.1 with full Elixir 1.14 support and mix formatted code

**Pull request closed without merging**
